import {KitCheckbox} from './Checkbox';
import {KitInput} from './Input';
import {KitInputNumber} from './InputNumber';
import {KitRadio} from './Radio';
import {KitRate} from './Rate';
import {KitSelect} from './Select';
import {KitTag} from './Tag';
import {KitSwitch} from './Switch';
import {KitDatePicker} from './DatePicker';
import {KitAutoComplete} from './AutoComplete';
import {KitUpload} from './Upload';
export {KitSlider} from './Slider';

export {KitCheckbox};
export {KitInput};
export {KitInputNumber};
export {KitRadio};
export {KitRate};
export {KitSelect};
export {KitTag};
export {KitSwitch};
export {KitAutoComplete};
export {KitDatePicker};
export {KitUpload};
