# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic"

# Event for the workflow
on:
  push:
    branches: [ '*' ]
    tags: ['*']
  pull_request:
    branches: [ '*' ]
    types: [labeled]

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.base_ref == 'develop' || github.base_ref == 'main') && contains(github.event.pull_request.labels.*.name, 'run chromatic')
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
        # 👇 Adds Chromatic as a step in the workflow
      - name: install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          onlyChanged: true # enables turboSnap
        env:
          CI: true