# .github/workflows/nightly.yml

# Workflow name
name: "Publish nightly Package to npmjs"

on:
  workflow_call:
  workflow_dispatch:
    secrets:
      NPM_TOKEN:
        description: 'Npm Token'
        required: false

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  build:
    uses: ./.github/workflows/build.yml
    needs: lint
  prepublish:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      nightly_version: ${{ steps.version.outputs.next_version }}
      exists: ${{ steps.check.outputs.exists }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'develop'
      - name: get next version
        id: version
        run: |
          echo ${{ github.ref_name}}
          echo "next_version=$(cat package.json | jq -r '.version')-$(git rev-parse --short develop)" >> "$GITHUB_OUTPUT"
          echo "next_version=$(cat package.json | jq -r '.version')-$(git rev-parse --short develop)" >> "$GITHUB_ENV"
      - name: Update package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: package.json
          field: version
          value: ${{ env.next_version }}
      - name: Check publish status
        id: check_npm
        uses: tehpsalmist/npm-publish-status-action@v1
      - name: set check npm variable
        id: check
        run: |
          echo "exists=${{ steps.check_npm.outputs.exists }}" >> "$GITHUB_OUTPUT"
  publish-nightly:
    runs-on: ubuntu-latest
    needs: prepublish
    if: ${{needs.prepublish.outputs.exists == '0'}}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'develop'
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Update package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: package.json
          field: version
          value: ${{ needs.prepublish.outputs.nightly_version }}
      - name: install dependencies
        run: yarn
      - name: build project
        run: yarn build
      - run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  build-storybook:
    runs-on: ubuntu-latest
    needs: [prepublish, publish-nightly]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'develop'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Update package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: package.json
          field: version
          value: ${{ needs.prepublish.outputs.nightly_version }}
      - name: install dependencies
        run: yarn
      - name: build-storybook
        run: STORYBOOK_DEPLOY=true yarn build-storybook
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'storybook-dev'
          path: ./storybook-static
