# Workflow name
name: Publish Package to npmjs

on:
  push:
    tags:
      - '*'

jobs:
  prepublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nowsprinting/check-version-format-action@v3
        id: version
      - uses: geritol/match-tag-to-package-version@0.2.0
        id: match-version
  publish-npm:
    runs-on: ubuntu-latest
    needs: prepublish
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-storybook:
    runs-on: ubuntu-latest
    needs: prepublish
    steps:
      - uses: actions/checkout@v4
      - name: build-storybook
        run: yarn && yarn build-storybook
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: storybook-main
          path: ./storybook-static