name: "Test Publish nightly Package to npmjs cron task"

on:
  workflow_dispatch:
  schedule:
    - cron: '0/45 * * * *'

jobs:
  nightly:
    uses: ./.github/workflows/nightly.yml
    secrets: inherit