# .github/workflows/chromatic.yml

# Workflow name
name: "Design system workflow"

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'develop'
    types: [synchronize, labeled]

jobs:
  eslint:
    uses: ./.github/workflows/Eslint.yml
  chromatic:
    if: github.event_name == 'pull_request' && github.base_ref == 'develop' && contains(github.event.pull_request.labels.*.name, 'run chromatic')
    needs: eslint
    uses: ./.github/workflows/chromatic.yml
    secrets: inherit
  npm:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: eslint
    uses: ./.github/workflows/npm.yml
    secrets: inherit
  storybook-main:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: npm
    uses: ./.github/workflows/storybook.yml
  storybook-dev:
    if: github.event_name == 'push' && github.ref_name == 'develop'
    needs: eslint
    uses: ./.github/workflows/storybook.yml